[package]
name = "tonic_server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net"] }
tonic = { version = "0.11", features = ["transport"] }
tokio-stream = { version = "0.1", features = ["net"] }
prost = "0.12"

[build-dependencies]
tonic-build = "0.11"
