use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};

fn main() -> Result<(), Box<dyn Error>> {
    let proto_root = PathBuf::from("protobuf_definitions");
    let generated_root = PathBuf::from("generated_rust");

    println!("cargo:rerun-if-changed={}", proto_root.display());

    let mut proto_files = Vec::new();
    collect_proto_files(&proto_root, &mut proto_files)?;
    proto_files.sort();

    fs::create_dir_all(&generated_root)?;

    clean_generated_directory(&generated_root)?;

    let mod_file_path = generated_root.join("generated_mod.rs");

    if proto_files.is_empty() {
        fs::write(
            &mod_file_path,
            "// This file is generated automatically and intentionally left blank because no .proto files were found.\n",
        )?;
        return Ok(());
    }

    let mut config = prost_build::Config::new();
    config.out_dir(&generated_root);
    config.compile_protos(&proto_files, &[proto_root])?;

    let mut module_source = String::from("// @generated by build.rs - do not edit manually.\n");
    for proto in &proto_files {
        if let Some(stem) = proto.file_stem().and_then(|s| s.to_str()) {
            let module_name = sanitize_module_name(stem);
            let output_file = generated_root.join(format!("{stem}.rs"));

            if !output_file.exists() {
                // `prost-build` only emits Rust sources when the `.proto` file
                // defines concrete messages. Service-only definitions (such as
                // `message_service.proto`) do not produce an output module, so
                // we skip generating an `include!` for those files.
                continue;
            }

            module_source.push_str(&format!(
                "pub mod {module_name} {{\n    include!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/generated_rust/{file}.rs\"));\n}}\n",
                module_name = module_name,
                file = stem,
            ));
        }
    }

    fs::write(&mod_file_path, module_source)?;

    Ok(())
}

fn collect_proto_files(dir: &Path, files: &mut Vec<PathBuf>) -> Result<(), Box<dyn Error>> {
    if !dir.exists() {
        return Ok(());
    }

    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();

        if path.is_dir() {
            println!("cargo:rerun-if-changed={}", path.display());
            collect_proto_files(&path, files)?;
        } else if path.extension().and_then(|ext| ext.to_str()) == Some("proto") {
            println!("cargo:rerun-if-changed={}", path.display());
            files.push(path);
        }
    }

    Ok(())
}

fn clean_generated_directory(dir: &Path) -> Result<(), Box<dyn Error>> {
    if !dir.exists() {
        return Ok(());
    }

    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_file() && path.extension().and_then(|ext| ext.to_str()) == Some("rs") {
            fs::remove_file(path)?;
        }
    }

    Ok(())
}

fn sanitize_module_name(stem: &str) -> String {
    let mut sanitized = String::new();

    for ch in stem.chars() {
        if ch == '_' || ch.is_ascii_alphanumeric() {
            sanitized.push(ch.to_ascii_lowercase());
        } else {
            sanitized.push('_');
        }
    }

    if sanitized.is_empty() {
        "generated_file".to_string()
    } else {
        sanitized
    }
}
